### ISSUE TITLE
shadowsocks + openwrt

### ISSUE THREAD

**Issue by ivanberry** [haoel/haoel.github.io#1]
皓哥什么时候可以考虑来个这个组合的教程:smile:

**Comment by haoel** [comment]
这个路由器也支持shadowsokcs的，不过我没有玩过。看看别人能不能补充一下。

**Comment by cunix** [comment]
一直是皓哥的粉丝，csdn,coolshell,weibo,wechat,感觉自己实在太low ,连visa什么的都没有,EC，linode都没有，现在翻墙还是自己弄比较靠谱。

**Comment by leozhang2018** [comment]
提个建议,关于 App store DNS 的问题,优化空间还有很多。
由于地域和运营商原因，指定 114 并不是最优解决方案，可以参考配合 https://github.com/gongjianhui/AppleDNS/ 融合到安装脚本
自动选择最优 DNS

**Comment by haoel** [comment]
@leozhang2018 谢谢，这个库我已玩过了，运行完后的itunes.apple.com的IP我配置上去了后，Apple Store无法使用了。我估计Apple的CDN也是经常变的，而这个库没有维护好。

**Comment by seasonscao** [comment]
除了华硕路由器，其他牌子的怎么刷呢？

**Comment by calmrund** [comment]
我测试了一下网件r6300v2梅林固件，按照配置可正常运行分流，一旦开启 shadowsocks 后貌似有冲突。SS显示国外线路异常。然后关闭掉SS开启VPN后，我访问国内线路提示我是美国IP（不过ping速度很快），访问淘宝也成了海外站。有可能两个dnsmasq互相影响。

目前没分析出原因，只有暂时恢复出厂设置使用@haoel 的稳定方案。
