### ISSUE TITLE
我不太同意这句话

### ISSUE THREAD

**Issue by csnever** [haoel/haoel.github.io#11]
“逻辑是这样的，如果你上了Google还是在用中文关键词，那么你科学上网有什么意义呢？”
现实情况是 就算用中文表达， 搜出来的中文资料也比 某搜索 更精准。 同样的关键词在 某搜索 中可能不存在、或者在第2，3页。  如果第一页就失望了，个人感觉基本上不会翻页看。 除非是 某类在线电影 网站。

**Comment by haoel** [comment]
OK, I will refine the statement.

And I want to clarify that I just want to guide the people much more close to the source of the knowledge...
