### ISSUE TITLE
Warp proxy pattern too many CLOSE_WAIT state

### ISSUE THREAD

**Issue by jnxyatmjx** [haoel/haoel.github.io#111]
how to address the issue that warp-svr have too many CLOSE_WAIT when use  -L wss://l:123@:443 -F socks5://127.0.0.1:40000 ？

**Comment by jnxyatmjx** [comment]
Temporary solution to this problem
kill -KILL pid 
restart warp-svc

**Comment by wspGreen** [comment]
It can't be restarted all the time, is there any other solution?

**Comment by haoel** [comment]
It's better open this issue to Cloudflare. And the workaround is set up a cron job to restart the service periodically.

**Comment by jnxyatmjx** [comment]
feedback the problem and temporary address the issure with crontab
