### ISSUE TITLE
CloudFlare TLS/SSL 设置是否前后不一致？

### ISSUE THREAD

**Issue by MountAye** [haoel/haoel.github.io#113]
第 3.3 节“使用 Cloudflare 的注意事项”中有：
> 在 CloudFlare 上，请将TLS/SSL设置为 完全

这里我理解“完全”是 Full

第 6.1 节：
> 注册 Cloudflare 帐号，并有一个空闲域名（三级域名即可），交给 Cloudflare 托管并将域名指向被封的 VPS IP，注意开启 Proxied 并且 SSL-TLS 使用 Flexible 选项。

这两者说的是不是同一件事？究竟应该选哪个？

---

我在不使用 Cloudflare 的情况下，已经配置成功。server 端是 Docker + GOST2.11, client 端是 Windows + GOST3.0 (GOST2 下载会报毒) + SwitchyOmega 

但是配置 Cloudflare 之后无法连通。直接把 3.3 节 Docker 脚本的最后一行 
```
-L "http2://${BIND_IP}:${PORT}?auth=${AUTH}&cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com"
```
换成
```
-L="mwss://${AUTH}@:443?cert=${CERT}\&key=${KEY}"
```
或者
```
-L="mwss://${AUTH}@:443?cert=${CERT}\&key=${KEY}&probe_resist=code:404&knock=www.google.com"
```

客户端根据 6.1 节修改后，连接时报错：
```
{"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:1984","msg":"127.0.0.1:13056 <> 127.0.0.1:1984","remote":"127.0.0.1:13056","service":"service-0","time":"2023-04-08T17:14:38.437-05:00"}
{"handler":"socks5","kind":"handler","level":"error","listener":"tcp","msg":"route(retry=0) 404 Not Found","service":"service-0","time":"2023-04-08T17:14:38.497-05:00"}
{"duration":59291600,"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:1984","msg":"127.0.0.1:13056 >< 127.0.0.1:1984","remote":"127.0.0.1:13056","service":"service-0","time":"2023-04-08T17:14:38.497-05:00"}
{"handler":"socks5","kind":"service","level":"error","listener":"tcp","msg":"404 Not Found","service":"service-0","time":"2023-04-08T17:14:38.497-05:00"}
```

我还在不断试错，下一步准备把 server 端也换成 3.0 版本。如果您知道问题出在哪，请您指教，谢谢。

**Comment by haoel** [comment]
请按第 3.3 节“使用 Cloudflare 的注意事项”中来设置！Regards,Hao在 2023年4月9日，06:24，Mount Aye ***@***.***> 写道：﻿
第 3.3 节“使用 Cloudflare 的注意事项”中有：

在 CloudFlare 上，请将TLS/SSL设置为 完全

这里我理解“完全”是 Full
第 6.1 节：

注册 Cloudflare 帐号，并有一个空闲域名（三级域名即可），交给 Cloudflare 托管并将域名指向被封的 VPS IP，注意开启 Proxied 并且 SSL-TLS 使用 Flexible 选项。

这两者说的是不是同一件事？究竟应该选哪个？

我在不使用 Cloudflare 的情况下，已经配置成功。server 端是 Docker + GOST2.11, client 端是 Windows + GOST3.0 (GOST2 下载会报毒) + SwitchyOmega
但是配置 Cloudflare 之后无法连通。直接把 3.3 节 Docker 脚本的最后一行
-L "http2://${BIND_IP}:${PORT}?auth=${AUTH}&cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com"

换成
-L="mwss://${AUTH}@:443?cert=${CERT}\&key=${KEY}"

或者
-L="mwss://${AUTH}@:443?cert=${CERT}\&key=${KEY}&probe_resist=code:404&knock=www.google.com"

客户端根据 6.1 节修改后，连接时报错：
{"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:1984","msg":"127.0.0.1:13056 <> 127.0.0.1:1984","remote":"127.0.0.1:13056","service":"service-0","time":"2023-04-08T17:14:38.437-05:00"}
{"handler":"socks5","kind":"handler","level":"error","listener":"tcp","msg":"route(retry=0) 404 Not Found","service":"service-0","time":"2023-04-08T17:14:38.497-05:00"}
{"duration":59291600,"handler":"socks5","kind":"handler","level":"info","listener":"tcp","local":"127.0.0.1:1984","msg":"127.0.0.1:13056 >< 127.0.0.1:1984","remote":"127.0.0.1:13056","service":"service-0","time":"2023-04-08T17:14:38.497-05:00"}
{"handler":"socks5","kind":"service","level":"error","listener":"tcp","msg":"404 Not Found","service":"service-0","time":"2023-04-08T17:14:38.497-05:00"}

我还在不断试错，下一步准备把 server 端也换成 3.0 版本。如果您知道问题出在哪，请您指教，谢谢。

**Comment by MountAye** [comment]
谢谢，根据 #28 的命令已经配置成功，没有指定 cert, key, probe_resist, 和 knock

但是在另一个网络环境里始终报错 bad handshake，感觉像是那个网络的问题，之前的报错也是在那个网络

建议把教程重构一下，现在的补丁已经影响到对文章的理解了
