### ISSUE TITLE
bypass后，openai依然无法使用

### ISSUE THREAD

**Issue by mymicroblog** [haoel/haoel.github.io#122]
耗子老师，
dockerfile如下：
docker run -d --name gost-warp \
    -v ${CERT_DIR}:${CERT_DIR}:ro \
    --net=host ginuerzh/gost \
    -L "http2://${USER}:${PASS}@${BIND_IP}:8443?cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com" \
    -F "socks5://localhost:40000?bypass=~*.openai.com,openai.com&notls=true"

openai能打开不再限制ip了，但是进去后依然无法使用

**Comment by haoel** [comment]
那就别 bypass 了

**Comment by mymicroblog** [comment]
![WechatIMG346](https://user-images.githubusercontent.com/3125442/232687343-beb3c4b0-8f0e-490a-aedf-8163eae3c7b0.jpeg)
用不用bypass都长这样

**Comment by haoel** [comment]
你在电脑上试试。

**Comment by mymicroblog** [comment]
./gost  -L ss://aes-128-gcm:passcode@:1984  -F 'https://user:pass@domain:8443' 
mac上有日志吗  没报错 ，用ss客户端连不上

**Comment by mymicroblog** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/3125442/232689584-348b8a99-d5a0-4d1f-aff2-75e387e73c19.png">
  用的 shadowsocksX-NG.app

**Comment by HenryLoveMiller** [comment]
客户端可以直接用 Proxy SwitchOmega 创建一个proxy 配置，不需要运行 shadowsocksX-NG.app 也行。

**Comment by HenryLoveMiller** [comment]
> 耗子老师， dockerfile如下： docker run -d --name gost-warp -v ${CERT_DIR}:${CERT_DIR}:ro --net=host ginuerzh/gost -L "http2://${USER}:${PASS}@${BIND_IP}:8443?cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com" -F "socks5://localhost:40000?bypass=~*.openai.com,openai.com&notls=true"
> 
> openai能打开不再限制ip了，但是进去后依然无法使用



> 耗子老师， dockerfile如下： docker run -d --name gost-warp -v ${CERT_DIR}:${CERT_DIR}:ro --net=host ginuerzh/gost -L "http2://${USER}:${PASS}@${BIND_IP}:8443?cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com" -F "socks5://localhost:40000?bypass=~*.openai.com,openai.com&notls=true"
> 
> openai能打开不再限制ip了，但是进去后依然无法使用

我实际验证了可行，方法为：

## 一、VPS 本地启动 Cloudflare Warp服务

## 二、gost docker 配置

```
#!/bin/bash

# 下面的四个参数需要改成你的
DOMAIN="you-domain.com"
USER="a-name"
PASS="a-password"
# 如果443被占用，ssl可以监听其他端口
PORT=443 


BIND_IP=0.0.0.0
CERT_DIR=/etc/letsencrypt
CERT=${CERT_DIR}/live/${DOMAIN}/fullchain.pem
KEY=${CERT_DIR}/live/${DOMAIN}/privkey.pem
docker run -d --name gost \
    -v ${CERT_DIR}:${CERT_DIR}:ro \
    --net=host ginuerzh/gost \
    -L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com" \
    -F "socks5://127.0.0.1:40000?bypass=~*.openai.com,openai.com&notls=true"
```

## 三、客户端

客户端可以直接用 Proxy SwitchOmega 创建一个proxy 配置，不需要运行 shadowsocksX-NG.app 也行。

![image](https://user-images.githubusercontent.com/119033012/232704400-fc45aab9-af44-48f7-b8b1-b0d8b8e0b779.png)
![image](https://user-images.githubusercontent.com/119033012/232704684-64346725-f94b-43a9-9dfa-babe92c9a270.png)
![image](https://user-images.githubusercontent.com/119033012/232704819-7646c91e-ece8-4eca-a1ed-54f39d98769e.png)

**Comment by HenryLoveMiller** [comment]
> > 耗子老师， dockerfile如下： docker run -d --name gost-warp -v ${CERT_DIR}:${CERT_DIR}:ro --net=host ginuerzh/gost -L "http2://${USER}:${PASS}@${BIND_IP}:8443?cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com" -F "socks5://localhost:40000?bypass=~*.openai.com,openai.com&notls=true"
> > openai能打开不再限制ip了，但是进去后依然无法使用
> 
> > 耗子老师， dockerfile如下： docker run -d --name gost-warp -v ${CERT_DIR}:${CERT_DIR}:ro --net=host ginuerzh/gost -L "http2://${USER}:${PASS}@${BIND_IP}:8443?cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com" -F "socks5://localhost:40000?bypass=~*.openai.com,openai.com&notls=true"
> > openai能打开不再限制ip了，但是进去后依然无法使用
> 
> 我实际验证了可行，方法为：
> 
> ## 一、VPS 本地启动 Cloudflare Warp服务
> 参见 https://github.com/haoel/haoel.github.io#942-%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F 9.4.2 代理模式
> 
> ## 二、gost docker 配置
> ```
> #!/bin/bash
> 
> # 下面的四个参数需要改成你的
> DOMAIN="you-domain.com"
> USER="a-name"
> PASS="a-password"
> # 如果443被占用，ssl可以监听其他端口
> PORT=443 
> 
> 
> BIND_IP=0.0.0.0
> CERT_DIR=/etc/letsencrypt
> CERT=${CERT_DIR}/live/${DOMAIN}/fullchain.pem
> KEY=${CERT_DIR}/live/${DOMAIN}/privkey.pem
> docker run -d --name gost \
>     -v ${CERT_DIR}:${CERT_DIR}:ro \
>     --net=host ginuerzh/gost \
>     -L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=code:404&knock=www.google.com" \
>     -F "socks5://127.0.0.1:40000?bypass=~*.openai.com,openai.com&notls=true"
> ```
> 
> ## 三、客户端
> 客户端可以直接用 Proxy SwitchOmega 创建一个proxy 配置，不需要运行 shadowsocksX-NG.app 也行。
> 
> ![image](https://user-images.githubusercontent.com/119033012/232704400-fc45aab9-af44-48f7-b8b1-b0d8b8e0b779.png) ![image](https://user-images.githubusercontent.com/119033012/232704684-64346725-f94b-43a9-9dfa-babe92c9a270.png) ![image](https://user-images.githubusercontent.com/119033012/232704819-7646c91e-ece8-4eca-a1ed-54f39d98769e.png)

@haoel 老师看看我这个客户端设置方法是否可行？

**Comment by haoel** [comment]
如果浏览器的SwitchOmegaProxy没问题，说明服务端是没有问题的，那问题就出在了客户端这边，你再看看客户端这边的事吧。

**Comment by gaoice** [comment]
开启warp后，出现聊天界面一直转圈加载不出 session 的情况，发现 https://chat.openai.com/api/auth/session 这个接口返回 {"detail":"Too many requests in 1 hour. Try again later."}，应该是 warp 的 ip 也开始被限制了

**Comment by mymicroblog** [comment]
是的。我也遇到了，不过把dockerfile中localhost改成127.0.0.1就好了

**Comment by mymicroblog** [comment]
> 开启 warp 后，也出现聊天界面一直转圈加载不出 session 的情况，发现 https://chat.openai.com/api/auth/session 这个接口返回 {"detail":"Too many requests in 1 hour. Try again later."}，应该是使用 warp 的人太多， ip 也开始被限制了。

是啊。我也是这个接口403，有办法解决吗

**Comment by ericjin07** [comment]
> > 开启 warp 后，也出现聊天界面一直转圈加载不出 session 的情况，发现 https://chat.openai.com/api/auth/session 这个接口返回 {"detail":"Too many requests in 1 hour. Try again later."}，应该是使用 warp 的人太多， ip 也开始被限制了。
> 
> 是啊。我也是这个接口403，有办法解决吗

使用warp 的代理同样会遇到这样的问题，使用 https://github.com/fscarmen/warp 配置的全局模式解决的。我用的是里面的warp-go

**Comment by mymicroblog** [comment]
> > > 开启 warp 后，也出现聊天界面一直转圈加载不出 session 的情况，发现 https://chat.openai.com/api/auth/session 这个接口返回 {"detail":"Too many requests in 1 hour. Try again later."}，应该是使用 warp 的人太多， ip 也开始被限制了。
> > 
> > 
> > 是啊。我也是这个接口403，有办法解决吗
> 
> 使用warp 的代理同样会遇到这样的问题，使用 https://github.com/fscarmen/warp 配置的全局模式解决的。我用的是里面的warp-go

全局模式全部流量都走cf，没问题吗，看耗子叔文档说容易连不上

**Comment by ericjin07** [comment]
暂时没有遇到连不上的问题。它里面也有非全局模式，走172.16.0.2的就行，需要用xray，至少gost 是做不到
