### ISSUE TITLE
gosh搭建完成，clash能正常使用，但是ios下载potatso里配置https无法使用

### ISSUE THREAD

**Issue by zws1992** [haoel/haoel.github.io#129]
ios除了ShadowRocket和potatso，还有啥好用的客户端吗？

**Comment by testername1994** [comment]
这俩就够用的了吧, 挺好用的

**Comment by haoel** [comment]
什么叫“好用”？另外，你觉得 ShadowRocket和potatso 哪 里不好用？

问问题的时候，要学会把自己的要注表达清楚，这样的表达完全让人不知道你到底要什么？
