### ISSUE TITLE
服务端采用gost代理，客户端Android手机还能继续像之前推荐德那样使用Shadowsocks+ShadowsocksGostPlugin吗？

### ISSUE THREAD

**Issue by Hanbing59** [haoel/haoel.github.io#131]
首先，谢谢耗叔不遗余力地更新这个repo。
几天前，我依照这个文档一步步操作，最终搭起了一个可用的服务：GoDaddy域名（形如xxxx.site，用的GoDaddy默认的域名服务器）+Google Cloud Platform虚拟机，Andorid客户端用的Shadowsocks+ShadowsocksGostPlugin。

后来，处于备份的考虑，又在GCP上开了一个虚拟机，并在GoDaddy上创建了一个A记录的subdomain，解析至新创建的虚拟机。然后就是按照同样的步骤一步步搭建服务端gost代理，但是在配置客户端后(与前一个虚拟机的配置基本一致，除了将Server配置成形如abc.xxxx.site的子域名)，却连不上，报错：Fail to detect internet connection: Unable to resolve host “cp.cloudflare.com”: No address associated with hostname。

今天，我看文档有更新，推荐采用Cloudflare进行域名解析，我便又注册Cloudflare，并在GoDaddy上修改了nameserver配置，并将GCP上两个虚拟机分贝采用形如abc.xxxx.site和def.xxxx.site的子域名进行解析。客户端配置与之前差不多，只是将Server对应修改为abc.xxxx.site和def.xxxx.site。结果，两个vps上的代理服务均连不上。

感觉应该是哪里我没有理解对，希望各位方便的时候能够给我一点clue，非常感谢！

**Comment by hnuzhoulin** [comment]
用cf之前，一个可以一个不可以，那应该 是不可以那个的配置有一些问题，比如服务端？可以用电脑 先尝试，看看日志，安卓看不到日志很麻烦。
cf那个如果 只是更换域名解析 ，应该跟gost没关系，按理不需要做什么 变化的。

**Comment by Hanbing59** [comment]
谢谢回复！我找到原因了，确实是我第二个的配置有问题。
