### ISSUE TITLE
Server 配置完成 但是公网一直连接不上

### ISSUE THREAD

**Issue by XRFate** [haoel/haoel.github.io#134]
server这边都打通了 测试curl 调用时候 也通过了 但是，从另一台机器测试curl 或者配置clash的时候总是显示timeout 

`ubuntu@ip-172-26-3-218:~$ curl -v "https://www.google.com" --proxy "XX.xx.xx:443" --proxy-user 'usr:pas'`

> Rebuilt URL to: https://www.google.com/
> Trying i.p.x.x...
> TCP_NODELAY set
> Connected to domain.name.com (x.x.x.x) port 443 (#0)
> allocate connect buffer!
> Establish HTTP proxy tunnel to www.google.com:443
> Proxy auth using Basic with user 'usr'
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> Proxy-Authorization: Basic a290b2tvX3Vzcjprb3Rva28yMDIz
> User-Agent: curl/7.58.0
> Proxy-Connection: Keep-Alive

下面是从公网的请求

> Rebuilt URL to: https://www.google.com/
>   Trying i.p.x.x...
> TCP_NODELAY set
> connect to x.x.x.x port 443 failed: Connection timed out
> Failed to connect to domain.name.com port 443: Connection timed out
> Closing connection 0`

clash 也timeout, 谢谢大大们解惑

**Comment by selfboot** [comment]
是不是你的vps有防火墙？不允许公网连443？

**Comment by XRFate** [comment]
> 是不是你的vps有防火墙？不允许公网连443？

AWS 的 Lightsail , 默认会有吗
