### ISSUE TITLE
咨询下 OLVPS 关于禁止用户跑代理软件的服务条款

### ISSUE THREAD

**Issue by gotnix** [haoel/haoel.github.io#16]
皓哥，您好！
正好最近在选 VPS 就发现这篇文章，先感谢下！总结下来 OLVPS NCP 线路的 VPS 的确不错，可是准备入手前看了眼《[服务条款](https://olvps.com/index.php?rp=/knowledgebase/1/TOS.html)》包含如下内容：

> 3.禁止使用用途：
> ……
> 8>禁止OpenV*P*N/Socks5/PPTP/L2TP等软件、公共代理
> ……
> 7.我方权利：
> 1>在用户违反第3条规定后，我方有权利进行删除服务。

请教下见多识广的皓哥，如果买了 VPS 能放心地用来跑代理么？现在处于想买但是买了又不太敢用的状态，皓哥指点一下！

**Comment by haoel** [comment]
Actually, OLVPS is not my company, so, you should write the email to them rather than me.

but just a quick guess, they probably worry about their IPs are blocked by the Wall, and they probably haven't got enough IP address……

--Hao

**Comment by haoel** [comment]
but I should mention this in this document... Thanks point it out!
