### ISSUE TITLE
设置GOST的时候 需要将域名映射到这台服务器吗

### ISSUE THREAD

**Issue by useaname** [haoel/haoel.github.io#25]
设置GOST的时候 需要将域名映射到这台服务器吗
还是解析保持购买之后的默认值就好

**Comment by haoel** [comment]
主要是你有没有let's encrypt 证书，如果有证书就需要绑域名

**Comment by useaname** [comment]
> 主要是你有没有let's encrypt 证书，如果有证书就需要绑域名

这个问题解决了。用docker方式启动的时候，执行后就exit了，centos7环境，没有看到错误信息。

**Comment by stefwoo** [comment]
我也遇到这个问题，是不是-v后面的“：ro”造成的？

**Comment by haoel** [comment]
docker 版本问题？
