### ISSUE TITLE
R.I.P 感谢耗子叔

### ISSUE THREAD

**Issue by zhanghexiangcn** [haoel/haoel.github.io#261]
花了半天时间参考教程搭建好了，再次感谢耗子叔留给我们的宝贵财富。

**Comment by zhanghexiangcn** [comment]
发现多台PC使用clash的时候会出现一直timeout的情况，处理了半天还是搞不定。最后换成 gost+shadowsocket 搞定了。

**Comment by ymichaelson** [comment]
> 发现多台PC使用clash的时候会出现一直timeout的情况，处理了半天还是搞不定。最后换成 gost+shadowsocket 搞定了。

你好gost+shadowsocket 这个怎么弄呀，我一直没处理好，能麻烦提供一下具体的配置和步骤吗，谢谢啦

**Comment by zhanghexiangcn** [comment]
> > 发现多台PC使用clash的时候会出现一直timeout的情况，处理了半天还是搞不定。最后换成 gost+shadowsocket 搞定了。
> 
> 你好gost+shadowsocket 这个怎么弄呀，我一直没处理好，能麻烦提供一下具体的配置和步骤吗，谢谢啦

前提是已经搭建好了服务器，并启动了gost服务。

1. [下载本地 gost 客户端](https://github.com/ginuerzh/gost/releases)，然后本地启动gost。进入gost安装目录，执行命令。
```
# 此处的ss服务端加密协议(eg: aes-128-gcm)必须是ss客户端支持的协议（来自耗子叔）
gost -L ss://aes-128-gcm:passcode@:1984 -F 'https://USER:PASS@DOMAIN:443'

# 因为我是win系统，对应的命令是
./gost-windows-amd64.exe -L ss://aes-128-gcm:密码@:端口 -F 'https://USER:PASS@DOMAIN:443'
```
2. 安装 Shadowsocks 客户端，可以到这里查看 [Shadowsocks Clients](https://github.com/shadowsocks)

* MacOS 上你可以下载 [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG/releases)
* Windows上你可以下载 [Shadowsocks-Windows](https://github.com/shadowsocks/shadowsocks-windows/releases)，需要先安装 [.NET Framework](https://dotnet.microsoft.com/download/dotnet-framework-runtime)

```
# 配置Shadowsocks
服务器地址：127.0.0.1
服务器端口：上一步中的`端口`
密码：上一步中的`密码`
加密：aes-128-gcm
```
然后系统代理选择PAC模式或者全局模式试试看。
