### ISSUE TITLE
aws+gost+https+patotso lite搭建不能访问

### ISSUE THREAD

**Issue by dream0411** [haoel/haoel.github.io#27]
按照文章里的gost方式的脚本，在aws ec2上搭建了服务端，配置好了域名、证书、非443的4位端口，ios端用patotso lite配置了一个https的方式，显示连接成功，但浏览器里还是不能访问google/twitter；

在服务端用这个证书和端口，开了个简单的python https目录服务器，浏览器里就能访问到内容；用户名和密码也确认没配置错；

试着用l2tp/IPSec，ios端能成功访问google等；

有人碰到过类似问题吗？

**Comment by haoel** [comment]
我试了一下，使用patotso lite 果然是有问题。目前没有查出来是什么原因。你换个客户端吧。我先改一下文档。
