### ISSUE TITLE
Cloudflare + gost遇到的问题

### ISSUE THREAD

**Issue by atbj505** [haoel/haoel.github.io#28]
使用Cloudflare 关闭proxied可以正常使用gost，如果打开proxied就会出现连接不通的情况，不知道大家有没有遇到过这种情况

**Comment by hanyunqi** [comment]
同问

**Comment by linshizuowei** [comment]
同问～

**Comment by atbj505** [comment]
目前已经切换到trojan，体验也还不错

**Comment by syt37du** [comment]
同问～
开proxied后ping域名是Cloudflare的ip，DNS only ping域名是vps的ip

**Comment by syt37du** [comment]
同样的问题，使用的方案是vps+gost+http2+rocket

以下是一些尝试，看能否提供一点解决思路

1. 使用install.sh脚本选项3生成证书时，Cloudflare Proxy status 只能为DNS only，如果使用Proxied申请的证书，则翻墙无法使用，这一点我看v2ray的教程中都强调了不能开proxy；
     可能原因是申请证书是域名解析到的不是VPS的ip，而是Cloudflare Proxy的ip
2.如果仅仅使用DNS only模式，那仅仅相当于将原来域名的NS换成了Cloudflare的NS而已，ping域名返回的还是vps 的ip，未达到隐藏vps ip的效果；换成Proxie(两种模式的切换生效很慢)后ping显示的是Cloudflare ip，但是此时翻墙无法使用

![image](https://user-images.githubusercontent.com/7856083/75505833-49600a80-5a17-11ea-81ff-1a607aa57cdc.png)
3.根据使用 CDN 中转的原理示意图，开始proxy后请问无法使用问题到底出现在哪里，同时应该怎么解决？请知道的麻烦提供一下方案和思路，谢谢！

**Comment by haoel** [comment]
Use ws if you want to use gost behind cloudflare.

**Comment by atbj505** [comment]
> Use ws if you want to use gost behind cloudflare.

@haoel 改成ws确实可以了，借鉴gost群里面的方法。遇到同样问题的朋友可以借鉴

server:
gost -L=mwss://user:password@:443

client:
gost -L socks5://:1080 -F mwss://user:password@yourdomain:443

cloudflare:
ssl/tls:full

**Comment by haoel** [comment]
@atbj505 我补充到文档中

**Comment by cdswyda** [comment]
> > Use ws if you want to use gost behind cloudflare.
> 
> @haoel 改成ws确实可以了，借鉴gost群里面的方法。遇到同样问题的朋友可以借鉴
> 
> server: gost -L=mwss://user:password@:443
> 
> client: gost -L socks5://:1080 -F mwss://user:password@yourdomain:443
> 
> cloudflare: ssl/tls:full

开 proxy 使用 mwss 是不是只能使用443端口？

试过其他端口，好像连接不上。

**Comment by atbj505** [comment]
> > > Use ws if you want to use gost behind cloudflare.
> > 
> > 
> > @haoel 改成 ws 确实可以了，借鉴 gost 群里面的方法。遇到同样问题的朋友可以借鉴
> > server: gost -L=mwss://user:password@:443
> > client: gost -L socks5://:1080 -F mwss://user:password@yourdomain:443
> > cloudflare: ssl/tls:full
> 
> @atbj505 开 proxy 使用 mwss 是不是只能使用 443 端口？
> 
> 试过其他端口，好像连接不上。

其他端口没试过，我看gost文档中mwss也是用的443。[Gost](https://v2.gost.run/ws/)

**Comment by bluenickle** [comment]
> Use ws if you want to use gost behind cloudflare.

请教一下改成ws以后，iOS端shadowrocket应该如何设置？试了https+gost插件好像不行

**Comment by bluenickle** [comment]
发完就发现已经搞定了。socks代理类型+gost插件可用

> > Use ws if you want to use gost behind cloudflare.
> 
> 请教一下改成ws以后，iOS端shadowrocket应该如何设置？试了https+gost插件好像不行
