### ISSUE TITLE
warp-cli参数更新

### ISSUE THREAD

**Issue by 1523789353** [haoel/haoel.github.io#290]
有关章节 `https://github.com/haoel/haoel.github.io?tab=readme-ov-file#104-cloudflare-warp-原生-ip`
cloudflare-warp v2024.2.62-1版本参数更新
```bash
#> warp-cli
CLI to the WARP service daemon

Usage: warp-cli [OPTIONS] <COMMAND>

Commands:
  connect               Maintain a connection whenever possible
  debug                 Debugging commands
  disconnect            Disconnect the client
  dns                   Configure DNS settings
  mdm                   MDM configs
  mode                  Set the client's general operating mode
  override              Allow temporary overrides of administrative settings
  proxy                 Configure proxy mode settings
  registration          Registration settings
  settings              Show or alter general application settings
  status                Return the current connection status
  trusted               Configure trusted networks where the client will be automatically disabled (Consumer only)
  tunnel                Configure tunnel settings
  vnet                  Get or specify connected virtual network
  generate-completions  Generate completions for a given shell and print to stdout
  help                  Print this message or the help of the given subcommand(s)

Options:
  -l, --listen      Listen for status changes and DNS logs (if enabled)
      --accept-tos  Accept the Terms of Service agreement
  -v, --verbose...  Enable verbose output. Multiple "v"s adds more verbosity
  -h, --help        Print help
  -V, --version     Print version
#> 
```

注册账号: `warp-cli registration new`
设定为代理模式: `warp-cli mode proxy`
连接WARP: `warp-cli connect`

永久启用命令不再可用: 
```bash
#> warp-cli enable-always-on
error: unrecognized subcommand 'enable-always-on'

  tip: some similar subcommands exist: 'enable-wifi', 'enable-dns-log'

Usage: warp-cli [OPTIONS] <COMMAND>

For more information, try '--help'.
#> 
```

还有，为什么都发rip啊...

**Comment by zhpjy** [comment]
发rip的原因，就是你想到的情况

**Comment by fgprodigal** [comment]
> 有关章节 `https://github.com/haoel/haoel.github.io?tab=readme-ov-file#104-cloudflare-warp-原生-ip` cloudflare-warp v2024.2.62-1版本参数更新
> 
> ```shell
> #> warp-cli
> CLI to the WARP service daemon
> 
> Usage: warp-cli [OPTIONS] <COMMAND>
> 
> Commands:
>   connect               Maintain a connection whenever possible
>   debug                 Debugging commands
>   disconnect            Disconnect the client
>   dns                   Configure DNS settings
>   mdm                   MDM configs
>   mode                  Set the client's general operating mode
>   override              Allow temporary overrides of administrative settings
>   proxy                 Configure proxy mode settings
>   registration          Registration settings
>   settings              Show or alter general application settings
>   status                Return the current connection status
>   trusted               Configure trusted networks where the client will be automatically disabled (Consumer only)
>   tunnel                Configure tunnel settings
>   vnet                  Get or specify connected virtual network
>   generate-completions  Generate completions for a given shell and print to stdout
>   help                  Print this message or the help of the given subcommand(s)
> 
> Options:
>   -l, --listen      Listen for status changes and DNS logs (if enabled)
>       --accept-tos  Accept the Terms of Service agreement
>   -v, --verbose...  Enable verbose output. Multiple "v"s adds more verbosity
>   -h, --help        Print help
>   -V, --version     Print version
> #> 
> ```
> 
> 注册账号: `warp-cli registration new` 设定为代理模式: `warp-cli mode proxy` 连接WARP: `warp-cli connect`
> 
> 永久启用命令不再可用:
> 
> ```shell
> #> warp-cli enable-always-on
> error: unrecognized subcommand 'enable-always-on'
> 
>   tip: some similar subcommands exist: 'enable-wifi', 'enable-dns-log'
> 
> Usage: warp-cli [OPTIONS] <COMMAND>
> 
> For more information, try '--help'.
> #> 
> ```
> 
> 还有，为什么都发rip啊...

人都没了

**Comment by 1523789353** [comment]
sad

**Comment by icedcoke** [comment]
You can use the “warp-cli settings list” command to view the configuration. If it displays "Always On: true", it is enabled by default and there is no need to execute the enable-always-on command.

別難過，哈哈哈。
