### ISSUE TITLE
GOST客户端

### ISSUE THREAD

**Issue by yudigithub** [haoel/haoel.github.io#40]
开始使用
```
gost -L ss://aes-128-cfb:passcode@:1984 -F 'https://USER:PASS@DOMAIN:443'
```
的时候报错：
```
**first path segment in URL cannot contain colon**
-------------------------------------------------------------------------------
```
后来用正面的命令可以了：
```
gost -L=ss://aes-128-cfb:123456@:1984 -F=https://user:passwd@ip:18260
```
记录一下，后面设置 的人可以看看

**Comment by vocano** [comment]
> ## 一开始使用
> gost -L ss://aes-128-cfb:passcode@:1984 -F 'https://USER:PASS@DOMAIN:443'
> 的时候报错：
> **first path segment in URL cannot contain colon**
> 后来用正面的命令可以了：
> gost -L=ss://aes-128-cfb:123456@:1984 -F=https://user:passwd@ip:18260
> 
> 记录一下，后面设置 的人可以看看


感谢提示，按照提示设置gost设置成功了
麻烦请教一下，按照haoel的文档介绍，先设置号gost后，本地SS需要怎么设置呢
我用127.0.0.1 设置后，CMD提示  ss.go:134: [ss] 127.0.0.1:53725 -> 127.0.0.1:8080 : Bad address type
我用服务器IP或者域名链接，没问题，但是感觉这种方式还是没有使用gost服务，
我使用的是script里面的安装脚本，安装了bbr/docker ce/SSL/GOST/SS

**Comment by yudigithub** [comment]
本地SS使用客户端配置&nbsp; 如“”“ss://aes-128-cfb:123456@:1984”，IP设置成127.0.0.1， 加密方式aes-128-cfb&nbsp; &nbsp; 密码用123456&nbsp; 端口用1984&nbsp;，然后再软件里面用代理设置成127.0.0.1 端口1080就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "vocano"<notifications@github.com&gt;; 
发送时间: 2020年3月7日(星期六) 上午10:25
收件人: "haoel/haoel.github.io"<haoel.github.io@noreply.github.com&gt;; 
抄送: "余迪"<1402364158@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [haoel/haoel.github.io] GOST客户端 (#40)



 
一开始使用
 
gost -L ss://aes-128-cfb:passcode@:1984 -F 'https://USER:PASS@DOMAIN:443'
 的时候报错：
 first path segment in URL cannot contain colon
 后来用正面的命令可以了：
 gost -L=ss://aes-128-cfb:123456@:1984 -F=https://user:passwd@ip:18260
 
记录一下，后面设置 的人可以看看
  
感谢提示，按照提示设置gost设置成功了
 麻烦请教一下，按照haoel的文档介绍，先设置号gost后，本地SS需要怎么设置呢
 我用127.0.0.1 设置后，CMD提示  ss.go:134: [ss] 127.0.0.1:53725 -&gt; 127.0.0.1:8080 : Bad address type
 我用服务器IP或者域名链接，没问题，但是感觉这种方式还是没有使用gost服务，
 我使用的是script里面的安装脚本，安装了bbr/docker ce/SSL/GOST/SS

**Comment by xinlmain** [comment]
2020年，我先试了Windows客户端。 这样的命令才成功…… 累死了！
-L=:1081  -F='https://GOST_USER:GOST_PWD@MY.DOMAIN:443' -F=ss://aes-256-cfb:SS_PWD@:SS_PORT

**Comment by ermeiyao** [comment]
出现ss.go:134: [ss] 127.0.0.1:53725 -> 127.0.0.1:8080 : Bad address type  的原因可能是，因为加密算法没设置对。

比如Shadowsocks-4.4.0.185 这个版本的Shadowsocks只支持aes-128-gcm而不是aes-128-cfb，所以cmd命令应该是：
```shell
gost -L ss://aes-128-gcm:passcode@:8089-F "https://USER:PASS@DOMAIN:443"
```
