### ISSUE TITLE
按照 3.3 用 gost 设置 HTTPS 服务，在Shadowrocket配置HTTPS不能正常上网

### ISSUE THREAD

**Issue by Bezss** [haoel/haoel.github.io#42]
系统 Centos7，服务器是搬瓦工的，在namesilo新买的域名，设置了域名解析，绑定到搬瓦工的服务器。

1、执行命令 sudo certbot certonly --standalone，获取证书成功。

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
to cancel): www.xxx.com
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/www.xxx.com.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Renewing an existing certificate

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/www.xxx.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/www.xxx.com/privkey.pem
   Your cert will expire on 2020-06-06. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

2、运行脚本成功。
```
#!/bin/bash

## 下面的四个参数需要改成你的
DOMAIN="www.xxx.com"
USER="abc"
PASS="abc9527"
PORT=6554

BIND_IP=0.0.0.0
CERT_DIR=/etc/letsencrypt
CERT=${CERT_DIR}/live/${DOMAIN}/fullchain.pem
KEY=${CERT_DIR}/live/${DOMAIN}/privkey.pem
sudo docker run -d --name gost \
    -v ${CERT_DIR}:${CERT_DIR}:ro \
    --net=host ginuerzh/gost \
    -L "http2://${USER}:${PASS}@${BIND_IP}:${PORT}?cert=${CERT}&key=${KEY}&probe_resist=code:404"
```

3、查看 gost 已经运行，docker -p -a。
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
03ae7266e36b        ginuerzh/gost       "/bin/gost -L http2:…"   41 minutes ago      Up 41 minutes                                gost
```

4、在苹果手机使用 Shadowrocket，翻不了qiang。添加 HTTPS 配置如下，
类型：HTTPS
服务器：106.203.63.147（域名对应ip地址）
port：6554
用户名：abc
密码：abc9527

大家有遇到相同问题吗？

**Comment by rampageX** [comment]
你建的 HTTP2 服务器为什么用 HTTPS 连接？Shadowrocket 可以连接 HTTP2 服务器。

**Comment by Bezss** [comment]
> 你建的 HTTP2 服务器为什么用 HTTPS 连接？Shadowrocket 可以连接 HTTP2 服务器。
> 
> 还有就是确认你的 6554 端口首先有没从 Docker 映射到主机，然后确认在主机防火墙打开没。
> 
> 最好远程先 tcping 一下 6554 端口，确认端口监听没问题。


谢谢，我知道问题出在哪里了：6554端口没有映射到主机。

1、我执行脚本出现一串数字
[root@perfect-fiber-1 ~]# ./gost.sh 
4e744e51fb73c8e86880aa45f96d1ec10b610cb915007079b06252cc2985bdd8

2、但是，docker ps -a 发现 port 为空
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
4e744e51fb73        ginuerzh/gost       "/bin/gost -L http2:…"   8 minutes ago       Up 8 minutes                                 gost

目前还不清楚是什么原因导致的。

**Comment by vocano** [comment]
> > 你建的 HTTP2 服务器为什么用 HTTPS 连接？Shadowrocket 可以连接 HTTP2 服务器。
> > 还有就是确认你的 6554 端口首先有没从 Docker 映射到主机，然后确认在主机防火墙打开没。
> > 最好远程先 tcping 一下 6554 端口，确认端口监听没问题。
> 
> 谢谢，我知道问题出在哪里了：6554端口没有映射到主机
> 
> 1、防火墙已经开启，并且使用 nc 命令查看，可以连接 6554 端口
> 
> 2、我执行脚本出现一串数字
> [root@perfect-fiber-1 ~]# ./gost.sh
> 4e744e51fb73c8e86880aa45f96d1ec10b610cb915007079b06252cc2985bdd8
> 
> 3、但是，docker ps -a 发现 port 为空
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> 4e744e51fb73 ginuerzh/gost "/bin/gost -L http2:…" 8 minutes ago Up 8 minutes gost
> 
> 目前还不清楚是什么原因导致的。

我遇到了跟你一样的问题，docker端口映射到主机需要怎么操作呢
用的是GCP Ubuntu 18.04

**Comment by vocano** [comment]
另外请教一下，Android https有什么软件可以使用吗，iPad上有装Shadowrocket

**Comment by haoel** [comment]
首先，当使用了 `--net=host` 后 `docker ps` 命令显示出来的 `PORTS` 列中是不会有信息的，因为不是端口映射！

如果你要看端口有没有侦听了，你应该使用  `netstat -nl` 命令来查看。

然后，如果你要看是否通了，你通过电脑先 `ping` 一下，然后再 `telnet <ip> <port>` 的方式。

**Comment by Bezss** [comment]
> 首先，当使用了 `--net=host` 后 `docker ps` 命令显示出来的 `PORTS` 列中是不会有信息的，因为不是端口映射！
> 
> 如果你要看端口有没有侦听了，你应该使用 `netstat -nl` 命令来查看。
> 
> 然后，如果你要看是否通了，你通过电脑先 `ping` 一下，然后再 `telnet <ip> <port>` 的方式。
> 
> > 另外请教一下，Android https有什么软件可以使用吗，iPad上有装Shadowrocket
> 
> https://github.com/xausky/ShadowsocksGostPlugin

1、服务器使用 netstat -nl 查看 6554 处于监听状态。使用命令 telnet 104.243.xxx.xxx 6554，发现端口也是通的，输出如下：
Trying 104.243.xxx.xxx...
Connected to 104.243.xxx.xxx.
Escape character is '^]'.

2、通过修改脚本参数 probe_resist=web:www.bing.com，可以打开 https://104.243xxx.xxx:6554，可以打开必应主页。所以可能是我手机上Shadowsocks配置有问题。

**Comment by vocano** [comment]
> > 首先，当使用了 `--net=host` 后 `docker ps` 命令显示出来的 `PORTS` 列中是不会有信息的，因为不是端口映射！
> > 如果你要看端口有没有侦听了，你应该使用 `netstat -nl` 命令来查看。
> > 然后，如果你要看是否通了，你通过电脑先 `ping` 一下，然后再 `telnet <ip> <port>` 的方式。
> > > 另外请教一下，Android https有什么软件可以使用吗，iPad上有装Shadowrocket
> > 
> > 
> > https://github.com/xausky/ShadowsocksGostPlugin
> 
> 1、服务器使用 netstat -nl 查看 6554 处于监听状态。使用命令 telnet 104.243.xxx.xxx 6554，发现端口也是通的，输出如下：
> Trying 104.243.xxx.xxx...
> Connected to 104.243.xxx.xxx.
> Escape character is '^]'.
> 
> 2、通过修改脚本参数 probe_resist=web:www.bing.com，可以打开 [https://104.243xxx.xxx:6554，可以打开必应主页。所以可能是我手机上Shadowsocks配置有问题。](https://104.243xxx.xxx:6554%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80%E5%BF%85%E5%BA%94%E4%B8%BB%E9%A1%B5%E3%80%82%E6%89%80%E4%BB%A5%E5%8F%AF%E8%83%BD%E6%98%AF%E6%88%91%E6%89%8B%E6%9C%BA%E4%B8%8AShadowsocks%E9%85%8D%E7%BD%AE%E6%9C%89%E9%97%AE%E9%A2%98%E3%80%82)


Android 可能问题
1.Shadowsocks启动提示：后台启动服务失败or 未知插件gost等无法连接，
手机系统默认不允许插件自启动的话也会出这个问题
以EMUI为例解决方法是 设置->应用->应用启动管理->ShadowsocksGostPlugin->手动管理->允许关联启动

2.正常配置
[插件下载：](https://github.com/xausky/ShadowsocksGostPlugin)
手机SS上IP和远程端口随便填，密码：gost，加密方式RC-MD5.
gost插件配置 -F https://USER:PASS@DOMAIN:443

**Comment by Bezss** [comment]
> > > 首先，当使用了 `--net=host` 后 `docker ps` 命令显示出来的 `PORTS` 列中是不会有信息的，因为不是端口映射！
> > > 如果你要看端口有没有侦听了，你应该使用 `netstat -nl` 命令来查看。
> > > 然后，如果你要看是否通了，你通过电脑先 `ping` 一下，然后再 `telnet <ip> <port>` 的方式。
> > > > 另外请教一下，Android https有什么软件可以使用吗，iPad上有装Shadowrocket
> > > 
> > > 
> > > https://github.com/xausky/ShadowsocksGostPlugin
> > 
> > 
> > 1、服务器使用 netstat -nl 查看 6554 处于监听状态。使用命令 telnet 104.243.xxx.xxx 6554，发现端口也是通的，输出如下：
> > Trying 104.243.xxx.xxx...
> > Connected to 104.243.xxx.xxx.
> > Escape character is '^]'.
> > 2、通过修改脚本参数 probe_resist=web:www.bing.com，可以打开 [https://104.243xxx.xxx:6554，可以打开必应主页。所以可能是我手机上Shadowsocks配置有问题。](https://104.243xxx.xxx:6554%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80%E5%BF%85%E5%BA%94%E4%B8%BB%E9%A1%B5%E3%80%82%E6%89%80%E4%BB%A5%E5%8F%AF%E8%83%BD%E6%98%AF%E6%88%91%E6%89%8B%E6%9C%BA%E4%B8%8AShadowsocks%E9%85%8D%E7%BD%AE%E6%9C%89%E9%97%AE%E9%A2%98%E3%80%82)
> 
> Android 可能问题
> 1.Shadowsocks启动提示：后台启动服务失败or 未知插件gost等无法连接，
> 手机系统默认不允许插件自启动的话也会出这个问题
> 以EMUI为例解决方法是 设置->应用->应用启动管理->ShadowsocksGostPlugin->手动管理->允许关联启动
> 
> 2.正常配置
> [插件下载：](https://github.com/xausky/ShadowsocksGostPlugin)
> 手机SS上IP和远程端口随便填，密码：gost，加密方式RC-MD5.
> gost插件配置 -F https://USER:PASS@DOMAIN:443

谢谢。不过我使用的是苹果手机，跟你情况不一样，我后来重新去购买域名的账户看了下，发现我的邮箱未验证。重新认证后，现在正常了。

**Comment by xmwen** [comment]
@Bezss 我安卓设备上配置成功了，但是在ios Shadowrocket没设置好。
请问里面的类型是跟搭建的http2服务器保持一致吗，需要设置gost插件吗？

**Comment by Bezss** [comment]
> @Bezss 我安卓设备上配置成功了，但是在ios Shadowrocket没设置好。
> 请问里面的类型是跟搭建的http2服务器保持一致吗，需要设置gost插件吗？

如果是https，苹果就选 https 类型，服务器要填写你的域名，不是ip地址。另外我问一下，安卓你用的也是 https 吗？有什么客户端推荐给我一下。

**Comment by xmwen** [comment]
> > @Bezss 我安卓设备上配置成功了，但是在ios Shadowrocket没设置好。
> > 请问里面的类型是跟搭建的http2服务器保持一致吗，需要设置gost插件吗？
> 
> 如果是https，苹果就选 https 类型，服务器要填写你的域名，不是ip地址。另外我问一下，安卓你用的也是 https 吗？有什么客户端推荐给我一下。

我之前是transport没设对，换成http+mws就好了。另外安卓我用的是上面推荐的socks+plugin用的http2

**Comment by ermeiyao** [comment]
我pc上能正常使用https那套方案，不过在华为手机，使用 Shadowsocks+ShadowsocksGostPlugin，显示连接成功，但是还是访问不了qiang外网站，这可能什么原因呢 @haoel

**Comment by jasnchng** [comment]
在iOS上如下配置Shadowrocket时遇到无法连接的问题
类型: HTTP2
地址: abc.xyz (填写为domain)
端口: 443
用户: username
密码: password
将地址由domain改为ip address后可以连接
被new bing提醒是DNS解析的问题, 在尝试将DNS配置由自动改为手动后, 填写domain也恢复正常连接.

**Comment by gzhh** [comment]
@jasnchng 请问下您换的是哪个 dsn 呢，我这边换了 233.5.5.5 这个还是不行。

**Comment by gzhh** [comment]
@jasnchng 我也是跟您类似的情况，但是换了几个 DNS 服务器都不正常，想请问下您用的是哪个 DNS 呢？

**Comment by anglezh** [comment]
> 在iOS上如下配置Shadowrocket时无法连接,
> 
> * 类型: HTTPS
> * 地址: {domain}
> * 端口: {port}
> * 用户: {username}
> * 密码: {password}
> 
> 尝试将地址由{domain}改为{ip_address}后, 连接正常. 怀疑是DNS解析的问题, 在设置中将配置DNS由自动切为手动后, {domain}和{ip_address}都可正常连接.



> 在iOS上如下配置Shadowrocket时无法连接,
> 
> * 类型: HTTPS
> * 地址：{域名}
> * 端口：{port}
> * 用户：{用户名}
> * 密码：{密码}
> 
> 尝试将地址由{domain}改为{ip_address}后,连接正常. 怀疑是DNS解析的问题,在设置中将配置DNS由自动切换为手动后,{domain}和{ip_address}拆迁

我一个新手。完全按照文档来的。把域名改成了IP，插件选择none成功了。

**Comment by hurner** [comment]
> 在iOS上如下配置Shadowrocket时无法连接,
> 
> * 类型: HTTPS
> * 地址: {domain}
> * 端口: {port}
> * 用户: {username}
> * 密码: {password}
> 
> 尝试将地址由{domain}改为{ip_address}后, 连接正常. 怀疑是DNS解析的问题, 在设置中将配置DNS由自动切为手动后, {domain}和{ip_address}都可正常连接.

我也遇到同样的问题。

之前一直使用上推荐的就能用，有很久一段时间没用后今天打开，发现不能用了。把地址那里从域名改为 IP 后，就可以了，不知道是什么原因。

你说的“在设置中配置 DNS”是在哪里？我怎么没找着

**Comment by hurner** [comment]
> > 在iOS上如下配置Shadowrocket时无法连接,
> > 
> > * 类型: HTTPS
> > * 地址: {domain}
> > * 端口: {port}
> > * 用户: {username}
> > * 密码: {password}
> > 
> > 尝试将地址由{domain}改为{ip_address}后, 连接正常. 怀疑是DNS解析的问题, 在设置中将配置DNS由自动切为手动后, {domain}和{ip_address}都可正常连接.
> 
> 我也遇到同样的问题。
> 
> 之前一直使用上推荐的就能用，有很久一段时间没用后今天打开，发现不能用了。把地址那里从域名改为 IP 后，就可以了，不知道是什么原因。
> 
> 你说的“在设置中配置 DNS”是在哪里？我怎么没找着

我猜是 shadowsocks 更新版本引入的

**Comment by DamianSheldon** [comment]
> 在iOS上如下配置Shadowrocket时无法连接,
> 
> * 类型: HTTPS
> * 地址: {domain}
> * 端口: {port}
> * 用户: {username}
> * 密码: {password}
> 
> 尝试将地址由{domain}改为{ip_address}后, 连接正常. 怀疑是DNS解析的问题, 在设置中将配置DNS由自动切为手动后, {domain}和{ip_address}都可正常连接.

正常使用过一段时间，某天突然不行了，不确定是升级系统还是升级 shadowsocks 的原因，地址由{domain}改为{ip_address}后, 连接正常。
