### ISSUE TITLE
Websocket + CDN 问题请教

### ISSUE THREAD

**Issue by snxly** [haoel/haoel.github.io#62]
感谢大大的指点，目前顺利搭建了 cdn + v2ray (websocket -> vmess) 的方案，用了两天，感觉不错。
有两个疑问还请指教：
1. 这个方案是不是理论上就杜绝了VPS的IP和端口被封禁的可能?
2. 关于iphone客户端
- websocket方案是不是没办法支持iphone客户端？
- 如果server侧暴露shadowsocks协议，有什么方案可以降低封禁概率吗？

**Comment by haoel** [comment]
1） 自建的方式并不代表不会封。因为用的人少所以被封的概率小。自建相比机场而言，对个人的安全性更高，因为机场有可能会拿你个人的隐私数据的。
2）关于iphone的客户端主要是要有代理的APP支持ws。一般还是用HTTPS
3）SS必被封，最好不要用，还是要用HTTPS的。
