### ISSUE TITLE
最下面的aws方案可能已经过时了

### ISSUE THREAD

**Issue by ficapy** [haoel/haoel.github.io#66]
NAT实例看文档已经要废弃掉了https://docs.aws.amazon.com/zh_cn/vpc/latest/userguide/VPC_NAT_Instance.html

变更成NAT网关了
文中的架构图可以参照该视频设置 https://www.youtube.com/watch?v=ujXr0i5EoHE

如果要实现文中的透明代理效果需要略作变更
只需要任意一台机器安装clash，设置好ip_forward

然后在需要的路由上添加192.18.0.0/16到该实例(注意该实例必须在 联网/源/目标检查 关闭检查)

其他的机器设置dns就可以使用代理了

**Comment by haoel** [comment]
NAT 实例没有废弃，只是废弃AMI。

另外，要在AWS内安装Clash，ip_forward肯定是要设置的，这是把一台主机变成路由器要设置的。但是内网里的所有服务器上的路由网关（default）都需要设置到这个实例上，这个事，必需在AWS 的 VPC的路由表里添加。其实，这就把这台机器变成了NAT实例。NAT网关是你完全看不见的补托管的。

**Comment by ficapy** [comment]
aws NAT 网关的主要作用是让私有子网能访问公网(公网不能创建连接到NAT网关)

如果没有NAT网关，私有子网需要访问公网应该就需要像文中那样创建NAT实例

**如果目的是全局透明代理**，假设VPC只有一个子网(而且是公有子网，并且分配公网ip,  都能够访问公网)
此时在该子网内任一机器部署一个clash，其他机器该如何使用这个代理呢
正常思维是就像我们在本地局域网那样部署，在其他机器添加下一跳网关，修改dns，但是会遇到一个问题
`ip route add xxxx/16 via xxx`
执行不报错，但是不起作用, 需要在部署clash的那台实例上关闭检查 -->> 联网/源/目标检查 关闭检查

关闭检查后该台机器即可以使用代理，但是这需要每一台机器都执行dns修改和添加下一跳路由，此时可以在VPC DHCP里面修改默认dns，可以在VPC路由表里面写入xx.xx.xx.xx/16到clash机器，就不需要给每台机器添加下一跳路由和修改dns了

如果子网大于两个以上，`ip route add xxxx/16 via xxx1` 这条语句会出错，因为xxx1和本机不在同一个网段，此时只能修改VPC路由，写入xx.xx.xx.xx/16下一跳为某机器

综上，创建透明代理和NAT实例和NAT网关没有什么关联，NAT网关的作用只不过是让私有子网能访问公网的一种手段

**Comment by haoel** [comment]
> **如果目的是全局透明代理**，假设VPC只有一个子网(而且是公有子网，并且分配公网ip, 都能够访问公网)
> 此时在该子网内任一机器部署一个clash，其他机器该如何使用这个代理呢

这个没有办法，因为AWS 的路由表需要在VPC里面配置的，你在EC2命令行上过一会就被VPC的刷新了，不起作用。但是，如果你在VPC里配路由，那是整个VPC子网都会受到影响，包括安装 clash 的那台机器。

**Comment by ficapy** [comment]
是的，创建一个网关就可以了..... 无论是用的什么手段😄
