### ISSUE TITLE
手机使用gost科学上网？

### ISSUE THREAD

**Issue by meiyingqishi** [haoel/haoel.github.io#81]
请问大家在手机上怎么用gost实现科学上网？

**Comment by isr4z6er** [comment]
- Shadowsock/SagerNet + GostPlugin
- Clash/Surfboard/ShadowRocket https 代理
- 安卓还可以直接termux本地跑gost

**Comment by meiyingqishi** [comment]
经过一番折腾，已通过 Shadowsocks Android + ShadowsocksGostPlugin 解决了。之前忘了后面的了。
