### ISSUE TITLE
new vpn

### ISSUE THREAD

**Issue by jnxyatmjx** [haoel/haoel.github.io#9]
I use  this website
 https://my.kynetwork.ltd/aff.php?aff=6797&gid=8
very useful!!

**Comment by haoel** [comment]
Thanks to provide this information, However, I am not sure the quality of kycloud service ( not like AWS, GCP, Linode...), so , I will leave this issue open here until the service is stable enough,  I will put this into the document. 

Thanks for understanding...

**Comment by nxtreaming** [comment]
Why do we  use your aff? @jnxyatmjx

**Comment by jnxyatmjx** [comment]
I will upload some pictures of Internet speed tonight，really very very fast @nxtreaming

**Comment by jnxyatmjx** [comment]
I use a USA cn2 gia speed like this
![VPN](https://user-images.githubusercontent.com/9018335/69429302-2fef5880-0d6e-11ea-8404-b1bc3161928c.png) @nxtreaming @haoel

**Comment by nxtreaming** [comment]
I do not hate VPN, I hate your aff!

Do you think others are blind?

**Comment by jnxyatmjx** [comment]
i am not sure if you are blind, but i am sure you lack practical ability! you can change the url? who care about you what hate,boy

**Comment by Vleyong** [comment]
> 
> 
> I do not hate VPN, I hate your aff!
> 
> Do you think others are blind?

Dude,you seem like a little bit irritable and .....information asymmetry leads to poor communication .More polite may be better
