### ISSUE TITLE
Warp安装教程从未成功

### ISSUE THREAD

**Issue by jnxyatmjx** [haoel/haoel.github.io#95]
在我的vps服务器上 不管脚本还是 手动安装都失败了，手动安装换成vps公网ip都失联了。

**Comment by haoel** [comment]
replace the manual installation with the proxy mode.

please try this 

https://github.com/[haoel/haoel.github.io](https://github.com/haoel/haoel.github.io#942-%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F)#942-%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F

**Comment by jnxyatmjx** [comment]
> replace the manual installation with the proxy mode.
> 
> please try this
> 
> [https://github.com/[haoel/haoel.github.io](https://github.com/haoel/haoel.github.io#942-%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F)#942-%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F](https://github.com/%5Bhaoel/haoel.github.io%5D(https://github.com/haoel/haoel.github.io#942-%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F)#942-%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F)

exactly, but in my vps I need set-proxy-port to start the socks5 proxy

**Comment by jnxyatmjx** [comment]
all works
