### ISSUE TITLE
原生IP是指互联网设备在网络中分配到的唯一的IP地址，而非该网站的IP地址和其机房的IP地址一致。关于 IDC 提供商的IP地址，虽然可能会从其他国家调配来，但是这并不会影响翻墙访问相关服务。

### ISSUE THREAD

**Issue by bensonjiang001** [haoel/haoel.github.io#98]
原生IP是指互联网设备在网络中分配到的唯一的IP地址，而非该网站的IP地址和其机房的IP地址一致。关于 IDC 提供商的IP地址，虽然可能会从其他国家调配来，但是这并不会影响翻墙访问相关服务。

**Comment by haoel** [comment]
Please give the reference, thanks!

**Comment by haoel** [comment]
no update, close it!
